# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Michael Wulff Nielsen
"""Convert PNG artwork to C source for the uSVC 8bpp tile mode.

Usage:
    uv run gfx.py tiles SHEET.png NAMES.txt OUT
    uv run gfx.py sprites SHEET.png FRAMES.txt OUT
    uv run gfx.py preview IMAGE.png OUT.raw

`tiles` slices SHEET.png into 8x8 tiles, left to right then top to bottom.
NAMES.txt has one tile name per line, in that order; the number of names is
the number of tiles. It writes OUT.c and OUT.h with the pixel data and one
`TILE_<NAME>` index per tile.

`sprites` cuts frames out of SHEET.png. FRAMES.txt has one frame per line:
`name x y width height [handle_x handle_y]` (the handle defaults to the
centre). It writes OUT.c and OUT.h with `spriteData`, `frameData` and one
`FRAME_<NAME>` index per frame. Transparent pixels (alpha below 128) become
0, which the kernel does not draw.

In both files `#` starts a comment.

`preview` scales any image to the 96x72 picture the game loader shows for a
package and writes it as raw pixel bytes, for `usc.py pack --preview`.
"""

import argparse
import sys
from pathlib import Path

from PIL import Image

TILE_SIZE = 8
ALPHA_THRESHOLD = 128
# Sprite pixel value 0 is transparent, so opaque black is stored as the
# darkest other colour (red level 1 of 7).
SPRITE_BLACK = 0x01
BYTES_PER_LINE = 16


def colour_byte(r: int, g: int, b: int) -> int:
    """Pixel byte for an RGB colour: 3 bits red, 3 green, 2 blue.

    The bit order follows the console's pin layout (COLOR_TORGB332 in the
    kernel's vgaConstants.h).
    """
    r3 = round(r * 7 / 255)
    g3 = round(g * 7 / 255)
    b2 = round(b * 3 / 255)
    return (
        (r3 & 1)
        | ((r3 & 4) >> 1)
        | ((r3 & 2) << 1)
        | ((b2 & 1) << 3)
        | ((g3 & 1) << 4)
        | ((b2 & 2) << 4)
        | ((g3 & 2) << 5)
        | ((g3 & 4) << 5)
    )


def read_lines(path: Path) -> list[list[str]]:
    """Non-empty lines of a text file, comments removed, split into words."""
    lines = []
    for raw in path.read_text().splitlines():
        words = raw.split("#", 1)[0].split()
        if words:
            lines.append(words)
    return lines


def c_name(name: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in name).upper()


def format_bytes(data: bytes, indent: str = "\t") -> str:
    rows = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        rows.append(indent + ", ".join(f"0x{b:02X}" for b in chunk))
    return ",\n".join(rows)


def region_bytes(image: Image.Image, x: int, y: int, w: int, h: int, sprite: bool):
    """Pixel bytes of a rectangle, row by row."""
    if x < 0 or y < 0 or x + w > image.width or y + h > image.height:
        raise ValueError(f"rectangle {x},{y} {w}x{h} is outside the image")
    out = bytearray()
    for py in range(y, y + h):
        for px in range(x, x + w):
            r, g, b, a = image.getpixel((px, py))
            value = colour_byte(r, g, b)
            if sprite:
                if a < ALPHA_THRESHOLD:
                    value = 0
                elif value == 0:
                    value = SPRITE_BLACK
            out.append(value)
    return bytes(out)


def guard(path: Path) -> str:
    """Include guard; prefixed so it cannot clash with a kernel header's."""
    return "GFX_" + c_name(path.name) + "_"


def convert_tiles(sheet: Path, names_file: Path, out: Path) -> None:
    image = Image.open(sheet).convert("RGBA")
    names = [words[0] for words in read_lines(names_file)]
    columns = image.width // TILE_SIZE
    if len(names) > columns * (image.height // TILE_SIZE):
        raise ValueError(f"{len(names)} names but the sheet has fewer tiles")
    tiles = []
    for i in range(len(names)):
        x, y = (i % columns) * TILE_SIZE, (i // columns) * TILE_SIZE
        tiles.append(region_bytes(image, x, y, TILE_SIZE, TILE_SIZE, sprite=False))

    header = out.with_suffix(".h")
    defines = "\n".join(f"#define TILE_{c_name(n)} {i}" for i, n in enumerate(names))
    header.write_text(
        f"/* Generated by tools/gfx.py from {sheet.name}. Do not edit. */\n"
        f"#ifndef {guard(header)}\n#define {guard(header)}\n#include <stdint.h>\n\n"
        f"#define NUM_ROM_TILES {len(names)}\n{defines}\n\n"
        f"extern const uint8_t tileData[NUM_ROM_TILES][64];\n\n#endif\n"
    )
    body = ",\n".join("\t{\n" + format_bytes(t, "\t\t") + "\n\t}" for t in tiles)
    out.with_suffix(".c").write_text(
        f"/* Generated by tools/gfx.py from {sheet.name}. Do not edit. */\n"
        f'#include "{header.name}"\n\n'
        f"const uint8_t tileData[NUM_ROM_TILES][64] =\n{{\n{body}\n}};\n"
    )
    print(f"{len(names)} tiles -> {out.with_suffix('.c')}")


def convert_sprites(sheet: Path, frames_file: Path, out: Path) -> None:
    image = Image.open(sheet).convert("RGBA")
    data = bytearray()
    frames = []
    for words in read_lines(frames_file):
        if len(words) not in (5, 7):
            raise ValueError(f"bad frame line: {' '.join(words)}")
        name = words[0]
        x, y, w, h = (int(v) for v in words[1:5])
        ox, oy = (int(v) for v in words[5:7]) if len(words) == 7 else (w // 2, h // 2)
        frames.append((name, w, h, ox, oy, len(data)))
        data += region_bytes(image, x, y, w, h, sprite=True)

    header = out.with_suffix(".h")
    defines = "\n".join(
        f"#define FRAME_{c_name(f[0])} {i}" for i, f in enumerate(frames)
    )
    header.write_text(
        f"/* Generated by tools/gfx.py from {sheet.name}. Do not edit. */\n"
        f"#ifndef {guard(header)}\n#define {guard(header)}\n#include <stdint.h>\n"
        f'#include "usvc_kernel/sprites.h"\n\n'
        f"#define NUM_SPRITE_PIXELS {len(data)}\n#define NUM_FRAMES {len(frames)}\n"
        f"{defines}\n\n"
        f"extern const uint8_t spriteData[NUM_SPRITE_PIXELS];\n"
        f"extern const frame_t frameData[NUM_FRAMES];\n\n#endif\n"
    )
    frame_rows = ",\n".join(
        f"\t{{ .w = {w}, .h = {h}, .ox = {ox}, .oy = {oy}, "
        f".pData = &spriteData[{offset}] }}"
        for _, w, h, ox, oy, offset in frames
    )
    out.with_suffix(".c").write_text(
        f"/* Generated by tools/gfx.py from {sheet.name}. Do not edit. */\n"
        f'#include "{header.name}"\n\n'
        f"const uint8_t spriteData[NUM_SPRITE_PIXELS] =\n{{\n{format_bytes(data)}\n}};\n\n"
        f"const frame_t frameData[NUM_FRAMES] =\n{{\n{frame_rows}\n}};\n"
    )
    print(f"{len(frames)} frames, {len(data)} bytes -> {out.with_suffix('.c')}")


PREVIEW_SIZE = (96, 72)


def convert_preview(image_path: Path, out: Path) -> None:
    image = Image.open(image_path).convert("RGBA")
    image = image.resize(PREVIEW_SIZE, Image.Resampling.LANCZOS)
    out.write_bytes(region_bytes(image, 0, 0, *PREVIEW_SIZE, sprite=False))
    print(f"preview {PREVIEW_SIZE[0]}x{PREVIEW_SIZE[1]} -> {out}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    sub = parser.add_subparsers(dest="command", required=True)
    for name, func in (("tiles", convert_tiles), ("sprites", convert_sprites)):
        cmd = sub.add_parser(name)
        cmd.add_argument("sheet", type=Path, help="PNG image")
        cmd.add_argument("listing", type=Path, help="names or frames text file")
        cmd.add_argument("out", type=Path, help="output path without extension")
        cmd.set_defaults(func=func)
    preview = sub.add_parser("preview")
    preview.add_argument("image", type=Path, help="any image; it is scaled")
    preview.add_argument("out", type=Path, help="output file (raw bytes)")
    args = parser.parse_args()
    try:
        if args.command == "preview":
            convert_preview(args.image, args.out)
        else:
            args.func(args.sheet, args.listing, args.out)
    except (OSError, ValueError) as err:
        print(f"error: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
